### ISSUE TITLE
Сontacts.html

### ISSUE THREAD

**Issue by BekbolotA** [TechScienceFest/TechScienceFest.github.io#1]
@nsaddambek, 
1.Please fix the spelling error(Google sForm) in the button to go to google form.
2.No icons for switching to social networks
3.Add an indent between the image and google map

**Comment by nsaddambek** [comment]
@BekbolotA I am done 1 and 3 but can't find how add icon for social networks

**Comment by BekbolotA** [comment]
@nsaddambek great!
