### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by BekbolotA** [TechScienceFest/TechScienceFest.github.io#2]
I noticed that all the headers are half red and the other half black, and there is also a heading "Основные направления изобретений в области" and in my opinion if it is done as well as on other headers it will be cool.

**Comment by TechScienceFest** [comment]
Actually, "Основные направления изобретений в области" header is part of information about festival. So that's why it meaningless to make it separately. This head has same goal as other part of head in about festival section.
