### ISSUE TITLE
No image in Wiki

### ISSUE THREAD

**Issue by BekbolotA** [TechScienceFest/TechScienceFest.github.io#20]
@kryspaeva why there is no image of the diagram?

**Comment by kryspaeva** [comment]
the diagram is in Russian, we need it in English

**Comment by Adakhan** [comment]
I added image

**Comment by Adakhan** [comment]
@bermet1325 Can you translate diagram?

**Comment by ghost** [comment]
yes, just a moment

**Comment by ghost** [comment]
I sent to the telegram
