### ISSUE TITLE
Mistake in Wiki

### ISSUE THREAD

**Issue by Adakhan** [TechScienceFest/TechScienceFest.github.io#24]
I found some grammatically and orthographically mistakes.

**Comment by kryspaeva** [comment]
the question for each member who have wrote!

**Comment by Adakhan** [comment]
I correct the whole documentation

**Comment by Adakhan** [comment]
@kryspaeva can you say which document files you don't need? Can we remove them?

**Comment by kryspaeva** [comment]
all the files related documentations can be removed, except wiki.

**Comment by Adakhan** [comment]
Ok
