### ISSUE TITLE
Order of sections in Wiki

### ISSUE THREAD

**Issue by Adakhan** [TechScienceFest/TechScienceFest.github.io#25]
@kryspaeva why sections in Wiki not ordered?

**Comment by kryspaeva** [comment]
only one of them. Because, the first section was empty...

**Comment by Adakhan** [comment]
so can we solve it?

**Comment by kryspaeva** [comment]
also, it depends on changes that each member makes. so, it depends on fortune lol

**Comment by Adakhan** [comment]
aa, ok
